### ISSUE TITLE
[Bug]: forcing dependency on pyyaml 6< to 5.4.1 gives cython issue while building version 5.4.1

### ISSUE THREAD

**Issue by mohamedaminch** [oracle/accelerated-data-science#263]
### Oracle-ads version used

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://https://github.com/oracle/accelerated-data-science/releases/) of oracle-ads.

- [X] I have confirmed this bug exists on the main branch of oracle-ads.

- [X] I agree to follow [Code of Conduct](https://github.com/oracle/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

installing latest version of oracle-ads, it has depency on pyyaml for version 6< (not =), and >5.4.1, so it takes 5.4.1 but with python 3.10 and 5.4.1 I'm getting a cython error : 

Collecting pyyaml==5.4 (from -r requirements.txt (line 1))
  Downloading PyYAML-5.4.tar.gz (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.8/174.8 kB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/mac/.pyenv/versions/3.10.1/envs/mwaa/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mac/.pyenv/versions/3.10.1/envs/mwaa/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/mac/.pyenv/versions/3.10.1/envs/mwaa/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(mwaa) mac@Mohameds-MacBook-Pro dpl-datapipelines-mwaa % pip install -r requirements.txt
Collecting pyyaml==5.3.1 (from -r requirements.txt (line 1))
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

### How to Reproduce

```python
using python 3.10

pip install oracle-ads
```

### What was Observed

Collecting pyyaml==5.4 (from -r requirements.txt (line 1))
  Downloading PyYAML-5.4.tar.gz (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.8/174.8 kB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/mac/.pyenv/versions/3.10.1/envs/mwaa/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mac/.pyenv/versions/3.10.1/envs/mwaa/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/mac/.pyenv/versions/3.10.1/envs/mwaa/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/v8/z7_rv36j4pb8_hzv3nzvqhmm0000gn/T/pip-build-env-anvl__aw/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(mwaa) mac@Mohameds-MacBook-Pro dpl-datapipelines-mwaa % pip install -r requirements.txt
Collecting pyyaml==5.3.1 (from -r requirements.txt (line 1))
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

### What was Expected

successful installation of oracle ads with pyyaml 6

### Version

2.8.7

I'm using a macbook pro M1 , but got the same issue on AWS linux based docker container.  (MWAA)

## Proposed solution : 

loosen the pyyaml versions to allow higher than version 6 or equal to version 6

**Comment by mrDzurb** [comment]
Hi [mohamedaminch](https://github.com/mohamedaminch), we are working on this problem. Will be fixed in the next version of ADS.

**Comment by liudmylaru** [comment]
PR: https://github.com/oracle/accelerated-data-science/pull/266
